config/routes.rb
Trackncheese::Application.routes.draw do
  root :to => "home#index"

	match '/calendar(/:year(/:month))' => 'calendar#index', as: :calendar, constraints: { year: /\d{4}/, month: /\d{1,2}/}, via: :all

	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get 'auth/failure', to: 'sessions#failure'
	get 'signin', to: 'sessions#new', as: 'new_session'
	get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :identities
  
	resources :projects do
		get 'single', on: :new
		get 'album',  on: :new
		resources :tasks do 
			member do
				get :toggle
			end
		end
		resources :songs do 
			resources :tasks do 
				member do 
					get :toggle
				end
			end
			resources :song_attachments
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		# two background images alternated every week (0.jpg, 1.jpg)
		@bg = "bg/#{Time.now.strftime("%U").to_i % 2}.jpg"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= content_for :page_bg do %>
    <%= image_tag @bg, alt: "", id: "bg" %>
<% end %>

<div class="row" style="margin-top: 80px">
	<div class="large-6 large-offset-3 columns" id="main-content">
		<div style="text-align: center">
			<h1>What do you want to accomplish?</h1>

			<%= link_to "Produce A Single", single_new_project_path, class: "radius button", "data-no-turbolink" => true %>
			<%= link_to "Produce An Album", album_new_project_path, class: "radius button", "data-no-turbolink" => true %>
		</div>
		
		<p>Something else? More project templates coming soon. Meanwhile,
			start with a <%= link_to "blank project", new_project_path, "data-no-turbolink" => true %>.</p>
	</div>
</div>

<div class="row">
	<div class="large-6 large-offset-3 columns" id="about">
		<p><strong>Track 'N Cheese</strong> is a project management system
			specifically designed for musician productivity. Built by
			musicians for musicians to just get things done.</p>
	</div>
</div>

<div style="text-align: center; margin-top: 16px;">
	<a href="https://twitter.com/trackncheese" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @trackncheese</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>