config/routes.rb
Trackncheese::Application.routes.draw do
  root :to => "home#index"

	match '/calendar(/:year(/:month))' => 'calendar#index', as: :calendar, constraints: { year: /\d{4}/, month: /\d{1,2}/}, via: :all

	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get 'auth/failure', to: 'sessions#failure'
	get 'signin', to: 'sessions#new', as: 'new_session'
	get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :identities
  
	resources :projects do
		get 'single', on: :new
		get 'album',  on: :new
		resources :tasks do 
			member do
				get :toggle
			end
		end
		resources :songs do 
			resources :tasks do 
				member do 
					get :toggle
				end
			end
			resources :song_attachments
		end
	end
end

app/models/song.rb
class Song < ActiveRecord::Base
	extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

	belongs_to :project, inverse_of: :songs
	acts_as_list scope: :project

  has_many :tasks, -> { order :due_on }, dependent: :destroy
  has_many :attachments, :class_name => "SongAttachment" #, :foreign_key => "song_id"

	validates :title, presence: true
	# validates :project_id, presence: true

  # Moving this to the controller so the song count is correct
  # when generating/scheduling tasks.
  # after_create :generate_tasks

  def slug_candidates
    [
      :title,
      [:title, :project_id],
      [:title, :project_id, :position]
    ]
  end

  def single?
    self.project.single?
  end

  # Here's some magic, setup the initial tasks for the song.
  # Magic is determining when the task is due based on the project finish goal
  # AND the position of this song related to the rest of the songs in the
  # project. The other magic is determining which tasks need to be generated
  # based on the project's configuration regarding how much of the
  # production (pre, post) is done.
  #
  def generate_tasks
    Task.generate_for(self)
  end

  def percent_complete
    return self.project.percent_complete if self.single?
    if completed_tasks.count > 0
      ( completed_tasks.count.to_f / tasks.count.to_f ) * 100.0
    else
      0
    end
  end

  def completed_tasks
    return self.project.project_wide_completed_tasks if self.single?
    @completed_tasks ||= tasks.where("completed_at IS NOT NULL AND completed_at <= ?", Date.tomorrow).order("completed_at DESC")
  end

  def incomplete_tasks
    return self.project.project_wide_incomplete_tasks if self.single?
    @incomplete_tasks ||= tasks.where("completed_at IS NULL OR completed_at > ?", Date.tomorrow).order("due_on ASC")
  end

  # Dynamically calculate the goal finish date of the song based on the project's
  # finish goal and the position of the song related to the rest of the
  # project's songs.
  #
  def finish_on
    return self.project.finish_on if self.single? 
    @finish_on ||= self.project.created_at.advance(days: project.song_interval_in_days * self.position).to_date
  end

  # What day to start working on this Song. (The day after previous song in the project ends)
  #
  def start_on
    return self.project.start_on if self.single?
    @start_on ||= (self.previous_song.is_a?(Song)) ? self.previous_song.finish_on.tomorrow : self.project.start_on
  end

  # How many days from start to finish to complete this Song
  #
  def days_to_complete
    (finish_on.to_date - start_on).to_i
  end

  # The song previous to this one in the project (if any)
  #
  def previous_song
    self.higher_item
  end

  # Determines if this song is late
  #
  def late?
    @late ||= (finish_on < Date.today) || self.late_tasks.length > 0
  end

  # Collects late tasks
  #
  def late_tasks
    @late_tasks ||= self.tasks.where(["due_on < ?", Date.today])
  end

  # Items for javascript calendar
  #
  def calendar_items
    @calendar_items ||= incomplete_tasks + [Task.new(name: "Finish song", due_on: self.finish_on)]
  end

  # The color for this item on the calendar
  #
  def color_for_calendar
    @color_for_calendar ||= CALENDAR_COLORS[self.position]
  end

  # List of words which might be useful for rhyming
  #
  def words_for_rhyming
    @words_for_rhyming ||= self.parse_lyrics_for_line_endings
  end

  # Parse the lyrics to come up with words for rhyming
  #
  def parse_lyrics_for_line_endings
    return [] if self.lyrics.blank?
    w = []
    self.lyrics.split(/\r\n|\r|\n/).each do |line|
      if word = line.split(/\s/).last
        word.gsub!(/[^a-zA-Z]/, "")
        w << word if word.length > 1
      end
    end
    w.uniq
  end

  # Suggest rhymes for each line of text in the song's lyrics
  #
  def rhyme_suggestions
    r = Rhymes.new
    rhymes = {}
    self.words_for_rhyming.each do |w|
      begin
        rhymes[w] = r.rhyme(w)
      rescue Rhymes::UnknownWord
        rhymes[w] = ["(no rhymes--unknown word)"]
      end
    end
    rhymes
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_filter :new_song, only: :create
	load_resource :project
	load_and_authorize_resource only: [:show, :new, :create, :update, :destroy]

	def show
		@element = [@project, @song, Task.new(song: @song)] # element for the new task form
		@song_attachment = SongAttachment.new
		@active_tab = params[:active_tab] || 'tasks'
		respond_to do |format|
			format.html
			format.json 
		end
	end

	def new		
	end

	def create
		@song.project = @project
		if @song.save
			redirect_to @project, notice: "Cool. Your song was added to the project."
		else
			render action: 'new'
		end
	end

	def update
		@already_active = 0 # 1 = collapses all accordions in the rhymer
		url_options = {}
		if params[:active_tab]
			url_options[:active_tab] = params[:active_tab]
		end
		if @song.update_attributes(safe_params)
			respond_to do |format|
				format.html {	redirect_to project_song_path(@project, @song, url_options) }
				format.js
			end
		else
			respond_to do |format|
				format.html { render action: 'show' }
				format.js { render json: ["there was a problem"] }
			end
		end
	end

	def destroy
		if @song.destroy
			redirect_to @project
		else
			redirect_to [@project, @song], alert: "There was a problem deleting the song."
		end
	end

private

	# Do this before cancan's methods so the strong parameters are in place.
	#
	def new_song
	  @song = Song.new(safe_params)
	end

	# Setup which params can be passed in via web forms
	#
	def safe_params
		params.require(:song).permit(:title, :lyrics)
	end

end

app/helpers/songs_helper.rb
module SongsHelper

	def rhyme_format(word)
		word.downcase.gsub(/\_/, ". ")
	end
end

app/views/songs/_form.html.erb
<%= simple_form_for [@project, @song] do |f| %>

	<%= f.input :title %>
	<%= f.submit "Add song to project", class: "medium round button" %>

<% end %>

app/views/songs/_rhymes.html.erb
<% @already_active ||= 0 %>
<% @song.rhyme_suggestions.each do |word, rhymes| %>
	<dd>
		<a href="#<%= word %>">"<%= word.to_s.upcase %>"</a>
		<div id="<%= word %>" class="content <%= 'active' unless @already_active > 0 %>">

			<ul id="rhymes_for_<%= word %>" class="rhymes">
				<% rhymes.sample(10).each do |r| %>
				<li><%= rhyme_format r %></li>
				<% end %>
			</ul>
		</div>
	</dd>
	<% @already_active = 1 %>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<div class="title row">
	<div class="large-9 columns">
		<h1><%= @song.title %></h1>
		<h6 class="subheader">Goal: finish by <%=l @song.finish_on, format: :long %>.
		<i>(<%= distance_of_time_in_words_to_now(@song.finish_on) %>
				<%= (@song.finish_on > Date.today) ? "from now" : "ago" %>)</i>
		</h6>
	</div>
	<div class="large-3 columns">
		<div style="text-align: right;">
			<% if @song.single? %>
				<%= link_to "delete project", @project, data: {confirm: "Are you sure? This cannot be undone." }, method: :delete, class: "delete" %>
				<%= link_to image_tag("icons-128/Symbol - Delete.png", alt: "", size: "24x24"), @project, data: {confirm: "Are you sure? This cannot be undone." }, method: :delete %>
			<% else %>
				<%= link_to "delete song", [@project, @song], data: { confirm: "Are you sure? This cannot be undone." }, method: :delete, class: "delete" %>
				<%= link_to image_tag("icons-128/Symbol - Delete.png", alt: "", size: "24x24"), [@project, @song], data: { confirm: "Are you sure? This cannot be undone." }, method: :delete %>
			<% end %>
			<br/><br/>
			<% if @song.single? %>
				<span data-tooltip class="has-tip" data-options="disable-for-touch:true" title="Add a song to the project">
					<%= link_to image_tag("icons-128/Symbol - Add.png", alt: "Add a song", size: "24x24"), new_project_song_path(@project) %>
				</span>
			<% end %>
		</div>
	</div>
</div>

<div class="tabs-container">
	<dl class="tabs" data-tab>
	  <dd <% if @active_tab && @active_tab == 'tasks' || @active_tab == nil %>class="active"<% end %>><a href="#taskscalendar">Tasks/Calendar</a></dd>
	  <dd <% if @active_tab && @active_tab == 'lyrics' %>class="active"<% end %>><a href="#lyrics">Lyrics</a></dd>
	  <dd <% if @active_tab && @active_tab == 'attachments' %>class="active"<% end %>><a href="#attachments">Attachments</a></dd>
	</dl>
</div>

<div class="tabs-content">
	<div class="content <% if @active_tab && @active_tab == 'tasks' || @active_tab == nil %>active<% end %>" id="taskscalendar">

		<div class="row">
			<div class="large-7 columns">

				<div class="task-list row">
					<div class="large-3 small-12 columns">
						<h5 class="subheader">Song Tasks</h5>
					</div>
					<div class="large-6 small-9 columns">
						<div class="progress success radius" id="task-counter-<%= @song.project_id %>" data-completedcount="<%= @song.completed_tasks.count %>" data-incompletecount="<%= @song.incomplete_tasks.count %>">
							<span class="meter" id="meter-<%= @song.project_id %>" style="width: <%=number_to_percentage @song.percent_complete, precision: 0 %>">
							</span>
						</div>
					</div>
					<div class="large-3 small-3 columns">
						<div class="status_container">
							<small id='percent-complete-<%=@song.project_id %>'><%=number_to_percentage @song.percent_complete, precision: 0 %> complete</small>
						</div>
					</div>
				</div>

				<div class="icon-actions">
					<%= link_to image_tag("icons-128/Symbol - Add.png", alt: "", size: "24x24"), new_project_song_task_path(@project, @song) %>
					<%= link_to "new task", new_project_song_task_path(@project, @song), data: { "reveal-id" => "new_task_modal" } %>
				</div>
				<ul id="task-list">
					<% @song.incomplete_tasks.each do |task| %>
					<li id="task_row_<%= task.id %>">
						<%= check_box_tag task.id, task.id, task.complete?, class: 'completer', 
							data: { 
								task: task.id, 
								project: (task.project) ? task.project_id : task.song.project_id,
								song: task.song_id,
								name: task.name, 
								due_on: I18n.l(task.due_on, format: :short)
							} %>
						<%= link_to task.name, edit_project_song_task_path(@song.project, @song, task) %>
						<%= content_tag :span, class: task.late? ? "late" : "" do %><i>due: <%=l task.due_on, format: :short %></i><% end %>
						<%= link_to(image_tag('trash.gif', alt: "delete task #{task.id}"), [@song.project, @song, task], method: :delete, data: { confirm: "Are you sure you want to delete the task?"} ) %>
					</li>
					<% end %>
				</ul>

				<h6 class="subheader" id='completed-tasks-title'>Completed Tasks
					(<%= @song.completed_tasks.count %>)</h6>
				<ul id="completed-tasks">
					<% @song.completed_tasks.each do |task| %>
					<li id="task_row_<%= task.id %>">
						<%= check_box_tag task.id, task.id, task.complete?, class: 'incompleter', 
							data: { 
								task: task.id, 
								project: (task.project) ? task.project_id : task.song.project_id,
								song: task.song_id,
								name: task.name, 
								due_on: I18n.l(task.due_on, format: :short)
							} %>
						<%= link_to task.name, edit_project_song_task_path(@song.project, @song, task) %>
						<i>completed: <%=l task.completed_at.to_date, format: :short %></i>
					</li>
					<% end %>
				</ul>
			</div>

			<div class="large-5 columns">
				<div id="calendar" data-events="<%= project_song_url(@project, @song, format: :json) %>" 
					data-year="<%= @song.start_on.year %>"
					data-month="<%= @song.start_on.month.to_i - 1 %>"
					data-date="<%= @song.start_on.day %>" >
				</div>

				<div class="ad-container">
				<%= google_adsense_include_tag client: ENV['ADSENSE_CLIENT'], slot: 'song_page_right_column', width: 300, height: 250 %>
				</div>

			</div>

		</div>
	</div>

	<div class="content <% if @active_tab && @active_tab == 'lyrics' %>active<% end %>" id="lyrics">
		<div class="row">
			<div class="large-8 columns">
				<h4>Use the space below as a scratchpad for your lyrics</h4>
				<%= simple_form_for [@project, @song], remote: true do |f| %>
					<%= hidden_field_tag :active_tab, 'lyrics' %>
					<%= f.input :lyrics, label: false, input_html: {rows: 20} %>
					<%= f.submit "Save lyrics", class: "medium round button" %>
				<% end %>
			</div>
			<div class="large-4 columns">
				<h4>Rhyme help <%= link_to image_tag('refresh-icon.png', alt: 'refresh', id: 'refresh_icon', size: '28x28'), [@project, @song], id: 'refresh_rhymes' %></h4>

				<dl class="accordion" id="rhymes" data-accordion>
					<% if @song.words_for_rhyming.length > 0 %>
						<%= render 'rhymes' %>
					<% else %>
						<i>Write a line or two and we'll suggest some rhymes.</i>
					<% end %>
				</dl>

			</div>
		</div>
	</div>

	<div class="content <% if @active_tab && @active_tab == 'attachments' %>active<% end %>" id="attachments">
		<div class="row">
			<div class="large-7 columns">
				<h4>Attachments <small>(demos, tracks, etc.)</small></h4>

				<ul class="file-list">
					<% @song.attachments.each do |att| %>
					<li> <%= link_to att.attachment_file_name, att.attachment.url %>
						<br/>
						<%= link_to image_tag("trash.gif", alt: 'delete'), [@project, @song, att], method: :delete, confirm: "Are you sure you want to delete the file?" %>
						<i>Uploaded: <%= l att.updated_at, format: :short %></i>
					</li>
					<% end %>
				</ul>
			</div>
			<div class="large-5 columns">
				<h6>New Attachment:</h6>
				<%= render 'song_attachments/form' %>
			</div>
		</div>
	</div>

</div>

<%= content_for :modals do %>
	<% if can? :create, Task.new(song: @song) %>
	<div id="new_task_modal" class="reveal-modal small" data-reveal>
		<h3>New Task:</h3>
		<%= render 'tasks/form' %>
		<a class="close-reveal-modal">&#215;</a>
	</div>
	<% end %>
<% end %>

<%= content_for :breadcrumbs do %>
	<% unless @song.single? %>
	<li><%= link_to @project.name, @project %></li>
	<% end %>
	<li class='current'><%= link_to @song.title, '#' %></li>
<% end %>

app/views/songs/update.js.erb
$('#rhymes').html('<%= j render("rhymes") %>')