config/routes.rb
Trackncheese::Application.routes.draw do
  root :to => "home#index"

	match '/calendar(/:year(/:month))' => 'calendar#index', as: :calendar, constraints: { year: /\d{4}/, month: /\d{1,2}/}, via: :all

	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get 'auth/failure', to: 'sessions#failure'
	get 'signin', to: 'sessions#new', as: 'new_session'
	get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :identities
  
	resources :projects do
		get 'single', on: :new
		get 'album',  on: :new
		resources :tasks do 
			member do
				get :toggle
			end
		end
		resources :songs do 
			resources :tasks do 
				member do 
					get :toggle
				end
			end
			resources :song_attachments
		end
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

	belongs_to :user
	attr_accessor :song_count
	has_many :songs, -> { order :position }, dependent: :destroy
	has_many :tasks, -> { order :due_on }, dependent: :destroy

	accepts_nested_attributes_for :songs

	after_create :generate_tasks

	# Instatiate a new album project with some default values.
	#
	def self.new_album(song_count=1)
		pname = (song_count == 1) ? 'My Single' : 'My Album'
		pname = "My Music Project" if song_count < 1
		new( 
			name: pname,
			preproduction: 0,
			production: 0,
			postproduction: 0,
			pushiness: 2,
			song_count: song_count,
			finish_on: song_count.months.from_now.to_date
		)
	end

	# Instatiate a new single song project with some default values.
	#
	def self.new_single
		new_album(1)
	end

	# Tries to load projects with an array of ids.
	#
	def self.try_to_load(project_ids)
		p = []
		[project_ids].flatten.each do |id|
			p << Project.find(id) if Project.exists?(id)
		end
		p
	end

  # Setup the initial tasks for the Project. (project-wide)
  #
  def generate_tasks
    Task.generate_for(self)
  end

  def percent_complete
    if project_wide_completed_tasks.length > 0
      ( project_wide_completed_tasks.length.to_f / project_wide_tasks.length.to_f ) * 100.0
    else
      0
    end
  end

  def completed_tasks
    @completed_tasks ||= tasks.where("completed_at IS NOT NULL AND completed_at <= ?", Date.tomorrow).order("completed_at DESC")
  end

  def incomplete_tasks
    @incomplete_tasks ||= tasks.where("completed_at IS NULL OR completed_at > ?", Date.tomorrow).order("due_on ASC")
  end

  def project_wide_completed_tasks
  	@project_wide_completed_tasks ||= project_wide_tasks.where("completed_at IS NOT NULL AND completed_at <= ?", Date.tomorrow).order("completed_at DESC")
  end

  def project_wide_incomplete_tasks
  	@project_wide_incomplete_tasks ||= project_wide_tasks.where("completed_at IS NULL OR completed_at > ?", Date.tomorrow).order("due_on ASC")
  end

  def project_wide_tasks
  	@project_wide_tasks ||= Task.where("project_id = ? OR song_id IN (?)", self.id, self.songs.pluck(:id))
  end

  def slug_candidates
    [
      :name,
      [:name, :created_at],
      [:name, :created_at, :user_id]
    ]
  end

	def song_count=(num)
		if num.to_i == 1
			self.songs << Song.new(title: self.name)
		else
			1.upto(num.to_i) {|i| self.songs << Song.new(title: "Song ##{i}") }
		end
	end

	def song_count
		self.songs.length
	end

	def single?
		song_count == 1
	end

	# The number of days for each song to be finished within the project
	#
	def song_interval_in_days
    @song_interval_in_days ||= case song_count
    	when 0 
    		days_to_complete
    	else
    		days_to_complete / song_count
    end
	end

	def start_on
		created_at.to_date
	end

	def days_to_complete
		(finish_on.to_date - start_on).to_i
	end

	def calendar_items(options={})
		@calendar_items ||= [self.songs, (options[:project_wide]) ? project_wide_incomplete_tasks : incomplete_tasks, Task.new(name: "Finish project", due_on: self.finish_on)].flatten
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :new_project, only: :create
	load_and_authorize_resource only: [:show, :create, :edit, :update, :destroy]

	# List all projects for current_user
	#
	def index	
	end

	# Show a Project.
	#
	def show
		@params = params # for json
		respond_to do |format|
			format.html { redirect_to [@project, @project.songs.first] if @project.single? }
			format.json 
		end
	end

	# Form for a new Project
	#
	def new
		@project ||= Project.new_album(0)
	end

	# Starts a new single song project with one month to
	# complete.
	#
	def single
		@project = Project.new_single
		render action: :new
	end

	# Starts a new album project. Default initiates 12 songs
	# and 12 months to complete.
	#
	def album
		@project = Project.new_album(12) 
		render action: :new
	end

	# Save the new project. Store the id in a cookie in case this user
	# doesn't have an account.
	#
	def create
		if user_signed_in?
			@project.user_id = current_user.id
		end
		if @project.save
			@project.songs.each { |s| s.generate_tasks }
			store_project_in_cookie(@project)
			redirect_to @project
		else
			render action: :new 
		end
	end

	# Load a project for editing
	#
	def edit
	end

	# Update (save changes) to a given project
	#
	def update
		if @project.update_attributes(safe_params)
			redirect_to @project
		else
			render action: "edit"
		end
	end

	def destroy
		if @project.destroy
			remove_project_from_cookie(@project)
			redirect_to projects_path
		else
			redirect_to @project, alert: "There was a problem deleting the project"
		end
	end

private

	# Do this before cancan's methods so the strong parameters are in place.
	#
	def new_project
	  @project = Project.new(safe_params)
	end

	# Setup which params can be passed in via web forms
	#
	def safe_params
		params.require(:project).permit(:name, 
			:finish_on, 
			:preproduction, 
			:production, 
			:postproduction, 
			:pushiness, 
			:song_count,
			songs_attributes: [
				:title, :finish_on, :id, :_destroy
			]
		)
	end

	# Keep the project id in the cookie.
	#
	def store_project_in_cookie(project)
		cookies.permanent.signed[:my_projects] ||= []
		projects = [cookies.permanent.signed[:my_projects]]
		projects << project.id
		cookies.permanent.signed[:my_projects] = projects.flatten
	end

	# Remove the project from the cookie.
	#
	def remove_project_from_cookie(project)
		cookies.permanent.signed[:my_projects] ||= []
		pids = cookies.permanent.signed[:my_projects]
		pids.delete(project.id)
		cookies.permanent.signed[:my_projects] = pids
	end

end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
	
	<% if @project.song_count == 1 %>
		<div class="row">
			<div class="large-12 columns">
				<%= f.input :name, label: "Project name" %>
			</div>
		</div>
		<%= f.input :song_count, as: :hidden %>

	<% else %>
		<div class="row">
			<div class="large-9 columns">
				<%= f.input :name, label: "Project name" %>
			</div>
			<div class="large-3 columns">
				<%= f.input :song_count, as: :integer, label: "How many songs?" %>
			</div>
		</div>

	<% end %>

	<div class="h-container">
		<h6>How much have you done already? <small>(if anything)</small></h6>
	</div>
	<div class="row">
		<div class="large-10 large-centered columns">
			<div class="row padded">
				<div class="large-3 small-4 columns">
					<label class="right-align">Pre-Production</label>
				</div>
				<div class="large-5 small-8 columns">
					<%= f.input :preproduction, 
						as: :range, 
						required: false,
						label: false,
						input_html: { min: 0, max: 10} %>
				</div>
				<div class="large-4 hide-for-small columns">
					<i class="smaller">(writing, practicing, arranging)</i>
				</div>
			</div>
			<div class="row padded">
				<div class="large-3 small-4 columns">
					<label class="right-align">Production</label>
				</div>
				<div class="large-5 small-8 columns">
					<%= f.input :production, 
						as: :range, 
						required: false,
						label: false,
						input_html: { min: 0, max: 10} %>
				</div>
				<div class="large-4 hide-for-small columns">
					<i class="smaller">(performing, recording)</i>
				</div>
			</div>
			<div class="row padded">
				<div class="large-3 small-4 columns">
					<label class="right-align">Post-Production</label>
				</div>
				<div class="large-5 small-8 columns">
					<%= f.input :postproduction, 
							as: :range, 
							required: false,
							label: false, 
							input_html: { min: 0, max: 10} %>
				</div>
				<div class="large-4 hide-for-small columns">
					<i class="smaller">(editing, mixing, mastering)</i>
				</div>
			</div>
		</div>
	</div>

	<div class="h-container">
 		<h6>When would you like to finish the project?</h6>
 	</div>
	<div class="row">
		<div class="large-6 large-centered columns">
			
			<div id="finish_on_picker" style="margin-bottom: 10px;" data-default="<%=l @project.finish_on.present? ? @project.finish_on : 1.month.from_now, format: :mmddyy %>"></div>
			<%= f.input :finish_on, as: :string, label: false %>
		</div>
	</div>

	<div class="h-container">
		<h6>How much of a push do you need to get it done?</h6>
	</div>
	<div class="row">
		<div class="large-10 large-centered columns">
			<div class="row padded">
				<div class="large-3 small-3 columns">
					<label class="right-align">little bit</label>
				</div>
				<div class="large-5 small-7 columns">
					<%= f.input :pushiness, 
							label: false,
							required: false,
							as: :range, 
							input_html: { min: 0, max: 3} %>
				</div>
				<div class="large-4 small-2 columns">
					<label>a lot</label>
				</div>
			</div>
		</div>
	</div>

	<div class="row" style="margin: 30px 0px">
		<div class="large-3 large-centered columns">
			<%= f.submit "Start Project", class: "radius button" %>
		</div>
	</div>
<% end %>

app/views/projects/edit.html.erb
<%= simple_form_for @project do |f| %>

<div class="row">
	<div class="large-8 columns">
		<h4><%= f.input :name, label: "Project Name:" %></h4>
	</div>
	<div class="large-4 columns">
		<h4><%= f.input :finish_on, label: "Goal to finish project:", as: :string %></h4>
	</div>
</div>

<div class="row">
	<div class="large-8 columns">

		<table style="width: 100%">
			<thead>
				<tr>
					<th>#</th>
					<th width="60%">Title</th>
					<th width="38%">Goal</th>
				</tr>
			</thead>
			<tbody>
				<% @project.songs.each_with_index do |song, i| %>
				<%= f.simple_fields_for :songs, song do |s| %>
				<tr>
					<td><%= i + 1 %></td>
					<td><%= s.input :title, label: false %></td>
					<td><%=l song.finish_on, format: :short %></td>
				</tr>
				<% end %>
				<% end %>
			</tbody>
		</table>

	</div>

	<div class="large-4 columns">
		<div style="text-align: center">
			<%= f.submit "Save Changes", class: "medium button round" %>
			<%= link_to "cancel", @project %>
		</div>
	</div>
</div>

<% end %>

app/views/projects/index.html.erb
<h1>My Projects</h1>

<div class="row">
	<div class="large-8 columns">
		<ul class="small-block-grid-2 large-block-grid-3">
			<% current_user.projects.uniq.each do |project| %>
			<li><div class="panel"><h6><%= link_to project.name, project %></h6>
				(<%= pluralize(project.songs.length, 'song') %>)
				<br/>goal: <%= l project.finish_on, format: :short %>
				<br/>0% done
			</div>
			</li>
			<% end %>
		</ul>
		<% if current_user.projects.length == 0 %>
		<p>There doesn't seem to be anything here. If you had created projects
			and don't see them, you probably just need to 
			<%= link_to "sign in", new_session_path %>.
		</p>
		<% end %>
	</div>
	<div class="large-4 columns">
		<% if !user_signed_in? && current_user.projects.length > 0 %>
		<div class="panel">
			<h4>Important!</h4>
			<p>You aren't logged in. We've put a cookie in your browser, so you'll be able
				to access your projects when you use this browser.<p>
			<p>However, you should <%= link_to "login or create an account", new_session_path %>
			 in order to take advantage of all the trackncheese functionality and to
			 guarantee you can access your projects
			 from any computer or device in the future.</p>
		</div>
		<% end %>
		<div class="panel">
			<h4>Start Something:</h4>
			<%= link_to "New Single", single_new_project_path, class: "tiny radius button", "data-no-turbolink" => true %>
			<%= link_to "New Album", album_new_project_path, class: "tiny radius button", "data-no-turbolink" => true %>
		</div>
	</div>
</div>

app/views/projects/new.html.erb
<div class="row" style="margin-top: 30px">
	<div class="large-8 large-offset-2 columns">
		<h3 style="text-align: center">The basics about your project:</h3>
		<%= render 'form' %>
	</div>
</div>

app/views/projects/show.html.erb
<div class="title row">
	<div class="large-10 columns">
		<h1><%= @project.name %></h1>
		<h6 class="subheader">Goal: finish by <%=l @project.finish_on, format: :long %>.
			<i>(<%= distance_of_time_in_words_to_now(@project.finish_on) %>
				<%= (@project.finish_on > Date.today) ? "from now" : "ago" %>)</i>
		</h6>
	</div>
	<div class="large-2 columns">
		<div style="text-align: right;">
			<%= link_to "delete project", @project, data: {confirm: "Are you sure? This cannot be undone." }, method: :delete, class: "delete" %>
			<%= link_to image_tag("icons-128/Symbol - Delete.png", alt: "Delete project", size: "24x24"), @project, data: {confirm: "Are you sure? This cannot be undone." }, method: :delete %>
		</div>
	</div>
</div>

<div class="row">
	<div class="large-7 columns">
		<div class="icon-actions">
			<span data-tooltip class="has-tip" data-options="disable-for-touch:true" title="Add a song">
				<%= link_to image_tag("icons-128/Symbol - Add.png", alt: "Add a song", size: "24x24"), new_project_song_path(@project) %>
			</span>
			<% if @project.song_count > 1 %>
			<span data-tooltip class="has-tip" data-options="disable-for-touch:true" title="Edit project and song titles">
				<%= link_to image_tag("icons-128/Edit.png", alt: "Quick edit", size: "24x24"), edit_project_path(@project) %>
			</span>
			<% end %>
		</div>
		<table style="width: 100%">
			<thead>
				<tr>
					<th>#</th>
					<th width="50%">Title</th>
					<th width="24%">Progress</th>
					<th width="24%" class="hide-for-small">Goal</th>
				</tr>
			</thead>
			<tbody>
				<% @project.songs.each_with_index do |song, i| %>
				<tr>
					<td><%= i + 1 %></td>
					<td><%= link_to song.title.present? ? song.title : "Untitled ##{i+1}", [@project, song],
					class: song.late? ? "late" : '' %></td>
					<td>
						<div class="progress success radius">
							<span class="meter" id="meter-<%= song.id %>" style="width: <%=number_to_percentage song.percent_complete, precision: 0 %>">
							</span>
							<small><%=number_to_percentage song.percent_complete, precision: 0 %> complete</small>
						</div>
					</td>
					<td class="hide-for-small"><%=l song.finish_on, format: :short %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<div class="task-list row">
			<div class="large-3 small-12 columns">
				<h5 class="subheader">Project Tasks</h5>
			</div>
			<div class="large-6 small-9 columns">
				<div class="progress success radius" id="task-counter-<%= @project.id %>" data-completedcount="<%= @project.project_wide_completed_tasks.length %>" data-incompletecount="<%= @project.project_wide_incomplete_tasks.length %>">
				<span class="meter" id="meter-<%= @project.id %>" style="width: <%=number_to_percentage @project.percent_complete, precision: 0 %>">
				</span>
				</div>
			</div>
			<div class="large-3 small-3 columns">
				<div class="status_container">
					<small id='percent-complete-<%=@project.id %>'><%=number_to_percentage @project.percent_complete, precision: 0 %> complete</small>
				</div>				
			</div>
		</div>


		<div class="icon-actions">
			<%= link_to image_tag("icons-128/Symbol - Add.png", alt: "", size: "24x24"), new_project_task_path(@project) %>
			<%= link_to "new task", new_project_task_path(@project) %>
		</div>
		<ul id="task-list">
			<% @project.incomplete_tasks.each do |task| %>
			<li id="task_row_<%= task.id %>">
				<%= check_box_tag task.id, task.id, task.complete?, class: 'completer', 
					data: { 
						task: task.id, 
						project: task.project_id,
						name: task.name, 
						# worker: (task.worker) ? task.worker.name : 'Unassigned',
						due_on: I18n.l(task.due_on, format: :short)
					} %>
				<%= link_to task.name, edit_project_task_path(@project, task) %>
				<i>due: <%=l task.due_on, format: :short %></i>
				<%= link_to(image_tag('trash.gif', alt: "delete task #{task.id}"), [@project, task], method: :delete, data: { confirm: "Are you sure you want to delete the task?"} ) %>
			</li>
			<% end %>
		</ul>

		<h6 class="subheader" id='completed-tasks-title'>Completed Tasks
			(<%= @project.completed_tasks.count %>)</h6>
		<ul id="completed-tasks">
			<% @project.completed_tasks.each do |task| %>
			<li id="task_row_<%= task.id %>">
				<%= check_box_tag task.id, task.id, task.complete?, class: 'incompleter', 
					data: { 
						task: task.id, 
						project: task.project_id,
						name: task.name, 
						# worker: (task.worker) ? task.worker.name : 'Unassigned',
						due_on: I18n.l(task.due_on, format: :short)
					} %>
				<%= link_to task.name, edit_project_task_path(@project, task) %>
				<i>completed: <%=l task.completed_at.to_date, format: :short %></i>
			</li>
			<% end %>
		</ul>
	</div>

	<div class="large-5 columns">

		<div id="calendar" data-events="<%= project_url(@project, project_wide: true, format: :json) %>"></div>

		<% if @project.user_id.blank? %>
		<div class="panel">
			<h4>Important!</h4>
			<p>Your project is not associated with your account. We've put a cookie
			in your browser, so you'll be able to return to the project when you
			use this browser.<p>
			
			<p>However, you should <%= link_to "login or create an account", new_session_path %>
			in order to take advantage of all the trackncheese functionality and to guarantee 
			you can access your project from any computer or device in the future.</p>
		</div>
		<% end %>

		<div class="ad-container">
		<%= google_adsense_include_tag client: ENV['ADSENSE_CLIENT'], slot: 'project_page_right_column', width: 300, height: 250 %>
		</div>

	</div>
</div>

<%= content_for :breadcrumbs do %>
	<li class="current"><a href="#"><%= @project.name %></a></li>
<% end %>