config/routes.rb
Trackncheese::Application.routes.draw do
  root :to => "home#index"

	match '/calendar(/:year(/:month))' => 'calendar#index', as: :calendar, constraints: { year: /\d{4}/, month: /\d{1,2}/}, via: :all

	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get 'auth/failure', to: 'sessions#failure'
	get 'signin', to: 'sessions#new', as: 'new_session'
	get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :identities
  
	resources :projects do
		get 'single', on: :new
		get 'album',  on: :new
		resources :tasks do 
			member do
				get :toggle
			end
		end
		resources :songs do 
			resources :tasks do 
				member do 
					get :toggle
				end
			end
			resources :song_attachments
		end
	end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% 
    css_class = 'alert-box'
    if name.match(/notice/i) 
      css_class += ' success'
    elsif name.match(/alert|warn/)
      css_class += ' alert'
    else
      css_class += ' secondary'
    end
  %>

    <%= content_tag :div, msg, class: css_class if msg.is_a?(String) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trackncheese" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Trackncheese" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield :page_bg %>

    <header>
      <div class="fixed">
        <nav class="top-bar" data-topbar>
          <ul class="title-area">
            <li class="logo">
              <%= link_to(image_tag("cheese_16.png", alt: "Track 'N Cheese musician project management"), root_path, "data-no-turbolink" => true) %> <%= link_to "Track 'N Cheese", root_path, :class => 'brand', "data-no-turbolink" => true %>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
          </ul>

          <section class="top-bar-section">
            <ul class="right">
              <% if user_signed_in? || cookies.permanent.signed[:my_projects] %>
                <li class="has-form"><%= link_to 'My Projects', projects_path, "data-no-turbolink" => true, class: "button" %></li>
                <li class="divider"></li>
              <% end %>
              <% if user_signed_in? %>
                <li class="has-form"><%= link_to 'Logout', signout_path, class: "button" %></li>
                  <% if current_user.has_role? :admin %>
                <li><%= link_to 'Admin', '#', "data-no-turbolink" => true %></li>
                  <% end %>
              <% else %>
                <li class="has-form"><%= link_to "Login/Signup", new_session_path, "data-no-turbolink" => true, class: "button" %></li>
              <% end %>
            </ul>
          </section>

        </nav>
      </div>
    </header>

    <div id="container" class="container">

      <div id="main" role="main" class="container">
        <div class="row">
          <div class="large-12 columns">
            <%= render 'layouts/messages' %>
            <% if content_for?(:breadcrumbs) %>
              <ul class="breadcrumbs">
                <li><a href="/projects">My Projects</a></li>
                <%= yield :breadcrumbs %>
              </ul>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>

    </div> 

    <footer>
    </footer>
    
    <%= yield :modals %>

    <%= javascript_include_tag "application" %>
  </body>
</html>